import { NextResponse } from 'next/server';
import { GDKpiRow } from '@/src/types/energy';

const MOCK_GD: GDKpiRow[] = [
  {
    id: 'kpi1',
    descricao: 'Vendas de GD Realizado x Esperado',
    unidade: '(MWh)',
    atualSemana: 553,
    targetMensal: 1895,
    atingimentoMensal: 57,
    acumuladoMes: 'acumulado mês atual: 1.076 MWh',
    confianca: 'success',
    semana: 29,
    evolution: [420, 480, 510, 553],
    targetAnual: 40441,
    atingimentoAnual: 7,
    acumuladoAno: 'acumulado ano: 2.771 MWh',
    hasVisaoSemanal: true,
  },
  {
    id: 'kpi2',
    descricao: 'Meta de Recebimento vs. Recebimento Efetivo',
    unidade: '(R$MM)',
    atualSemana: 3.6,
    targetMensal: 10.7,
    atingimentoMensal: 51,
    acumuladoMes: 'acumulado mês atual: R$ 5.4 MM',
    confianca: 'success',
    semana: 1.8,
    evolution: [3.2, 3.4, 3.5, 3.6],
    targetAnual: 161.5,
    atingimentoAnual: 11,
    acumuladoAno: 'acumulado ano: R$ 17.4 MM',
    hasVisaoSemanal: true,
  },
  {
    id: 'kpi3',
    descricao: 'Recebimento NEWCO / Energia Fácil / Bitcoin',
    unidade: '(R$ mil)',
    atualSemana: 0,
    targetMensal: 1238,
    atingimentoMensal: 0,
    acumuladoMes: 'acumulado mês atual: –',
    confianca: 'destructive',
    semana: null,
    evolution: [0, 0, 0, 0],
    targetAnual: 28702,
    atingimentoAnual: 1,
    acumuladoAno: 'acumulado ano: R$ 191 k',
    hasVisaoSemanal: true,
  },
  {
    id: 'kpi4',
    descricao: 'Distrato em usinas',
    unidade: '(R$ MM)',
    atualSemana: 3.3,
    targetMensal: 11.7,
    targetMensalNota: 'Target ano dividido por 12',
    atingimentoMensal: 69,
    acumuladoMes: 'acumulado mês atual: R$ 8.1 MM',
    confianca: 'warning',
    semana: -1.5,
    evolution: [4.2, 3.9, 3.6, 3.3],
    targetAnual: 140.2,
    atingimentoAnual: 11,
    acumuladoAno: 'acumulado ano: R$ 14.9 MM',
    hasVisaoSemanal: true,
  },
  {
    id: 'kpi5',
    descricao: 'Crédito de GD acumulados',
    unidade: '(GWh)',
    atualSemana: 386,
    atualSemanaLabel: 'Resultado Janeiro',
    targetMensal: 374,
    targetMensalLabel: 'Target Janeiro',
    atingimentoMensal: 3,
    isExtrapolado: true,
    acumuladoMes: 'acumulado mês atual: –',
    confianca: 'warning',
    semana: null,
    targetAnual: 671,
    atingimentoAnual: 0,
    acumuladoAno: 'acumulado ano: 386 GWh',
    hasVisaoSemanal: false,
  },
  {
    id: 'kpi6',
    descricao: 'Nº de UCs Ativas',
    unidade: '(# mil clientes)',
    atualSemana: 18.6,
    atualSemanaLabel: 'Resultado Janeiro',
    targetMensal: 22.8,
    targetMensalLabel: 'Target Janeiro',
    atingimentoMensal: 82,
    acumuladoMes: 'acumulado mês: 18.6 mil clientes',
    confianca: 'success',
    semana: null,
    targetAnual: 325.6,
    atingimentoAnual: 6,
    acumuladoAno: 'acumulado ano: 18.6 mil clientes',
    hasVisaoSemanal: false,
  },
];

export async function GET() {
  return NextResponse.json({
    success: true,
    data: MOCK_GD,
  });
}
